### Create a new User
// @no-cookie-jar 
POST http://localhost:3333/users
Content-Type: application/json

{
  "email":"victor5502@teste.com",
  "name":"Victor",
  "password":"123456"
}

### Login a new User
// @no-cookie-jar 
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email":"victor5502@teste.com",
  "password":"123456"
}

### GET  validate jwt
GET http://localhost:3333/me
Content-Type: application/json
Authorization: Bearer tokenRequsteSession
